name: Build and Push Docker Image

on:
  workflow_dispatch:


#on:
  #push:
    #branches:
      #- main
    #paths:
      #- '**.py'
      #- 'Dockerfile'
      #- 'requirements.txt'
      -# 'analyzer_config.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourusername/pii-anonymizer-api:latest
